# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leaf1) {transformation: [-0.5657f,0f,0.5657f,0f,0f,0.8f,0f,0f,-0.5657f,0f,-0.5657f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf2) {transformation: [-0.5657f,0f,0.5657f,0f,0f,0.8f,0f,0f,-0.5657f,0f,-0.5657f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf3) {transformation: [-0.5657f,0f,0.5657f,0f,0f,0.8f,0f,0f,-0.5657f,0f,-0.5657f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf4) {transformation: [-0.5657f,0f,0.5657f,0f,0f,0.8f,0f,0f,-0.5657f,0f,-0.5657f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.8f,0f,0f,0f,0f,0.797f,0.0697f,0.9754f,0f,0.0697f,-0.797f,-0.0426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stem2) {transformation: [-0.8f,0f,0f,0f,0f,0.7878f,0.1389f,0.483f,0f,0.1389f,-0.7878f,-0.1294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stem1) {transformation: [-0.8f,0f,0f,0f,0f,0.7727f,-0.2071f,0f,0f,-0.2071f,-0.7727f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}