# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.peashooter.root] run return 0
execute on passengers if entity @s[tag=aj.peashooter.data] unless data entity @s {data:{rigHash: '467cf0bf4d91ba115737831dc7c390fbc22ba14c2cff6047b66a0ef151e0f3ce'}} on vehicle run function animated_java:peashooter/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1