# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sunflower.root] run return 0
execute on passengers if entity @s[tag=aj.sunflower.data] unless data entity @s {data:{rigHash: '0861e29c02bc2dd4d9e124f7c3b7df50176e86f0ba0868f32d69c142bba7de3e'}} on vehicle run function animated_java:sunflower/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1