# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.zombie.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'zombie', 'function_path': 'animated_java:zombie/variants/cone/apply'}
execute on passengers if entity @s[tag=aj.zombie.bone.right_leg] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_right_leg
execute on passengers if entity @s[tag=aj.zombie.bone.left_leg] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.zombie.bone.body] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.zombie.bone.left_arm] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.zombie.bone.right_arm] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.zombie.bone.cone] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_cone
execute on passengers if entity @s[tag=aj.zombie.bone.bucket] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_bucket
execute on passengers if entity @s[tag=aj.zombie.bone.head] run function animated_java:zombie/variants/cone/zzz/apply_to_bone_head
return 1