# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.zombie.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'zombie', 'function_path': 'animated_java:zombie/animations/eat/play'}
tag @s add aj.zombie.animation.eat.playing
scoreboard players set @s aj.eat.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:zombie/animations/eat/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only