# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.zombie.root] run return 0
execute on passengers if entity @s[tag=aj.zombie.data] unless data entity @s {data:{rigHash: 'e3a6f2c6e3623df1b531b832e9daa8315bddb7b30665ba74e534d5558dfe921a'}} on vehicle run function animated_java:zombie/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1