# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.zombie.root] run return 0
execute on passengers if entity @s[tag=aj.zombie.data] unless data entity @s {data:{rigHash: 'bca5b8657de016a73140910078d456fe8b0d42ac21fe15aab69006584acb8a6e'}} on vehicle run function animated_java:zombie/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1