# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leaf1) {transformation: [-0.7778f,0f,0.7778f,0f,0f,1.1f,0f,0f,-0.7778f,0f,-0.7778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf2) {transformation: [-0.7778f,0f,0.7778f,0f,0f,1.1f,0f,0f,-0.7778f,0f,-0.7778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf3) {transformation: [-0.7778f,0f,0.7778f,0f,0f,1.1f,0f,0f,-0.7778f,0f,-0.7778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaf4) {transformation: [-0.7778f,0f,0.7778f,0f,0f,1.1f,0f,0f,-0.7778f,0f,-0.7778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaves) {transformation: [-1.1f,0f,0f,0f,0f,1.099f,0.048f,1.059f,0f,0.048f,-1.099f,0.0576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1f,0f,0f,0f,0f,1.099f,0.048f,0.9918f,0f,0.048f,-1.099f,0.0203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stem2) {transformation: [-1.1f,0f,0f,0f,0f,1.0337f,0.3762f,0.4985f,0f,0.3762f,-1.0337f,-0.2324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_stem1) {transformation: [-1.1f,0f,0f,0f,0f,0.9969f,-0.4649f,0f,0f,-0.4649f,-0.9969f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}