# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.eat.frame dummy
scoreboard objectives add aj.death.frame dummy