# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.leaf1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leaf1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.leaf2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leaf2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.leaf3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leaf3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.leaf4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leaf4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.stem2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_stem2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.peashooter.node.stem1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_stem1 set from storage aj:uuid main.out