# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation: [0f,0f,0f,-0.1187f,0f,0f,0f,0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [0f,0f,0f,0.1187f,0f,0f,0f,0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.125f,0f,0f,0f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [0f,0f,0f,0.3125f,0f,0f,0f,0.125f,0f,0f,0f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.125f,0f,0f,0f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cone) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,-1.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bucket) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,-1.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,-1.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:zombie/animations/death/zzz/frames/55_root_commands